### ISSUE TITLE
touchable on firefox for android

### ISSUE THREAD

**Issue by benranck** [dotmaster/Touchable-jQuery-Plugin#3]
Seems to not respond to the touch events at all. Just tried with the latest marketplace release of firefox.

**Comment by dotmaster** [comment]
thanks for the report, at the moment I am short on time to look into it, but might suggest you to try out http://www.vodori.com/blog/phantom-limb.html.

**Comment by benranck** [comment]
Cool, I might take a deeper look at your code anyway, because it's a
great idea. Not sure if I am able to help, but I'd like to.
Cheers,
Benjamin

On 22 June 2011 18:34, dotmaster
reply@reply.github.com
wrote:

**Comment by dotmaster** [comment]
awesome!! always appreciate help :)
